baseurl = "http://localhost:1313"
languageCode = "pt-br"
paginate = 4
theme = "iglu"
title = "André Lug - Digital nômade, lifestyle e trabalho freelancer"
enableRobotsTXT = true
defaultContentLanguage = "pt"
[blackfriday]
hrefTargetBlank = true
[params]
date_format = "0002-01-20T00:00:00+00:00"
description = "Blog sobre estilo de vida como nômade digital, trabalho freelancer e empreendedorismo. Cheio de dicas e ideias para quem quer ser livre na vida e no trabalho."
insta_caption = "{{caption}}"
insta_comments = "{{comments}}"
insta_img = "{{image}}"
insta_likes = "{{likes}}"
insta_link = "{{link}}"
name = "André Lug - Digital nômade, lifestyle e trabalho freelancer"
[params.featured]
hide = false
[params.recentposts]
hide = false
[permalinks]
pages = "/:filename"
posts = "/:filename"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
[author]
name = "André Lug"
